encryption:
  enabled: true
  key: "this is a super secure key"
sync:
  graphs:
    - C:\Users\schrist\OneDrive\Logseq\Personal
  interval: -1
  once: true
server:
  host: http://192.168.178.64:3000
  # host: http://localhost:3000
